#!/bin/sh

ENABLED=yes
PROCS=pimd
ARGS="-N -c /opt/etc/pimd.conf"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
